version: 2.1

jobs:
  test:
    docker: 
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: echo "this is the test job"

workflows:
  test:
    jobs:
      - test

